### ISSUE TITLE
Library support for java too

### ISSUE THREAD

**Issue by dineshmm23** [aniketbhoite/MutativeFab#8]
I tried to implement the project with java android project. It didn't work. All android library was getting *unable to resolve errors*.

**Comment by aniketbhoite** [comment]
have you added 
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
in app gradle?

**Comment by dineshmm23** [comment]
yes , I have added the project library as per setup..

**Comment by aniketbhoite** [comment]
Check your Kotlin plugin version, it should be 1.2.41 or above and your Constraint-layout dependency version should be 1.1.0 or above.
Still issue is not resolved share your Project and app gradle code here

**Comment by aniketbhoite** [comment]
I have tested and I am still able to build this lib in java project. 
I am closing this issue for now, If you still have this issue open issue again
